// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'contentParallax': string;
  'contentText': string;
  'contentWrap': string;
  'heading': string;
  'heroDesc': string;
  'root': string;
}
export const cssExports: CssExports;
export default cssExports;
