// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'activeLink': string;
  'headerLogo': string;
  'navigation': string;
  'navigationLink': string;
  'navigationList': string;
  'root': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
