// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'footerLabel': string;
  'footerLink': string;
  'root': string;
  'wrap': string;
}
export const cssExports: CssExports;
export default cssExports;
