// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'inputWrap': string;
  'pokemonList': string;
  'root': string;
  'searchInput': string;
  'title': string;
}
export const cssExports: CssExports;
export default cssExports;
